version: '2.1'
services:
  perfectpick-ldap:
    image: osixia/openldap:1.1.8
    container_name: PerfectPick_LDAP
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "PerfectPick"
      LDAP_DOMAIN: "perfectpick.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER_ENABLED: "false"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      #LDAP_REPLICATION_CONFIG_SYNCPROV: "binddn="cn=admin,cn=config"bindmethod=simple credentials=$LDAP_CONFIG_PASSWORD searchbase="cn=config"type=refreshAndPersist retry="60 +" timeout=1 starttls=critical"
      #LDAP_REPLICATION_DB_SYNCPROV: "binddn="cn=admin,$LDAP_BASE_DN"bindmethod=simple credentials=$LDAP_ADMIN_PASSWORD searchbase="$LDAP_BASE_DN"type=refreshAndPersist interval=00:00:00:10 retry="60 +" timeout=1starttls=critical"
      #LDAP_REPLICATION_HOSTS:"#PYTHON2BASH:['ldap://ldap.example.org','ldap://ldap2.example.org']"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "perfectpick.co"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: PerfectPick_LDAP_Client
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "perfectpick-ldap"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_SERVER_COMMAND: "true"
      PHPLDAPADMIN_ENABLE_AUTH_CMD: "true"
    ports:
    - "8085:80"
    links:
    - perfectpick-ldap